__version__ = '0.0.1'
__description__ = 'Natural language processing active learning library for data-driven AI'
__url__ = 'https://github.com/makcedward/nlpatl'
__author__ = 'Edward Ma'
__author_email__ = 'makcedward@gmail.com'